--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- PROJECT      : Student Management System (SMS) - Oracle SQL
-- MODULE       : 02 - Create Tables
-- DESCRIPTION  : Creates all 8 tables with Oracle-specific syntax.
--                Includes one SEQUENCE per table for primary key generation.
--                Tables are created in dependency order to satisfy FK constraints.
-- AUTHOR       : Zuhaib Khan
-- SCHEMA       : Pakistani University Context
--------------------------------------------------------------------------------
-- TABLE CREATION ORDER (dependency-safe):
--   1. DEPARTMENTS   (no dependencies)
--   2. PROGRAMS      (depends on DEPARTMENTS)
--   3. TEACHERS      (depends on DEPARTMENTS)
--   4. COURSES       (depends on PROGRAMS, TEACHERS)
--   5. STUDENTS      (depends on PROGRAMS)
--   6. ENROLLMENTS   (depends on STUDENTS, COURSES)
--   7. GRADES        (depends on ENROLLMENTS)
--   8. ATTENDANCE    (depends on STUDENTS, COURSES)

-- -----------------------------------------------------------------------------
-- TABLE 1: DEPARTMENTS
-- The root table. Everything in the university belongs to a department.
-- No foreign keys here — this is where the chain starts.
-- -----------------------------------------------------------------------------

-- Sequence: generates dept_id values (100,105,110, ...)
-- START WITH 100 : first value is 100
-- INCREMENT BY 5: goes up by 5 each time
-- NOCACHE       : don't pre-allocate values (safe for small datasets)
-- NOCYCLE       : stop if max value is reached (don't restart from 1)
CREATE SEQUENCE dept_seq
    START WITH 100
    INCREMENT BY 5
    NOCACHE
    NOCYCLE;
    
    
 CREATE TABLE DEPARTMENTS 
 (
    dept_id     NUMBER(5)       NOT NULL,       -- PK: populated via dept_seq.NEXTVAL on INSERT
    dept_name   VARCHAR2(100)   NOT NULL,       -- e.g. 'Computer Science', 'Electrical Engineering'
    dept_code   VARCHAR2(10)    NOT NULL,       -- Short code e.g. 'CS', 'EE', 'BBA'
    established DATE,                           -- When was this dept founded? Optional.
    -- PRIMARY KEY constraint: enforces uniqueness + creates an index automatically
    CONSTRAINT pk_departments PRIMARY KEY (dept_id),
    
    -- dept_code must be unique across all departments
    CONSTRAINT uq_dept_code UNIQUE (dept_code)
    );
    
 COMMENT ON TABLE  DEPARTMENTS           IS 'Top-level academic departments of the university';
 COMMENT ON COLUMN DEPARTMENTS.dept_id   IS 'Primary key, generated by dept_seq';
 COMMENT ON COLUMN DEPARTMENTS.dept_code IS 'Short unique code used in forms and reports';
 -------------------------------------------------------------------------------
 -------------------------------------------------------------------------------
-- TABLE 2: PROGRAMS
-- A department can offer multiple degree programs.
-- e.g. CS dept offers BSCS, MSCS; BBA dept offers BBA, MBA.
 CREATE SEQUENCE programs_seq
    START WITH 500
    INCREMENT BY 2
    NOCACHE
    NOCYCLE;

CREATE TABLE PROGRAMS (
    program_id      NUMBER(5)       NOT NULL,
    dept_id         NUMBER(5)       NOT NULL,       -- FK ? DEPARTMENTS: which dept runs this program
    program_name    VARCHAR2(150)   NOT NULL,       -- e.g. 'Bachelor of Science in Computer Science'
    program_code    VARCHAR2(20)    NOT NULL,       -- e.g. 'BSCS', 'MBA', 'BEE'
    degree_level    VARCHAR2(20)    NOT NULL,       -- 'Undergraduate' or 'Postgraduate'
    duration_years  NUMBER(2,1)     NOT NULL,       -- e.g. 4, 2.5 — supports half-years
    total_credits   NUMBER(5)       NOT NULL,       -- Total credit hours required to graduate
    
    CONSTRAINT pk_programs      PRIMARY KEY (program_id),
    CONSTRAINT uq_program_code  UNIQUE (program_code),
    
    -- CHECK: degree_level must be one of these two values only
    CONSTRAINT chk_degree_level CHECK (degree_level IN ('Undergraduate', 'Postgraduate')),
    
    -- CHECK: a program must be at least 1 year and no more than 6 years
    CONSTRAINT chk_duration CHECK (duration_years BETWEEN 1 AND 6),
    
    -- FK: dept_id must exist in DEPARTMENTS
    -- ON DELETE RESTRICT (default): cannot delete a dept if programs exist under it
    CONSTRAINT fk_programs_dept FOREIGN KEY (dept_id) REFERENCES DEPARTMENTS(dept_id)
);

COMMENT ON TABLE  PROGRAMS                  IS 'Degree programs offered by each department';
COMMENT ON COLUMN PROGRAMS.degree_level     IS 'Undergraduate or Postgraduate only';
COMMENT ON COLUMN PROGRAMS.duration_years   IS 'Supports decimals e.g. 2.5 years';

--------------------------------------------------------------------------------
-- TABLE 3: TEACHERS
-- Faculty members, each belonging to one department.
-- A teacher can teach multiple courses (handled via COURSES.teacher_id FK).

CREATE SEQUENCE teachers_seq
    START WITH 1000
    INCREMENT BY 3
    NOCACHE
    NOCYCLE;
    
CREATE TABLE TEACHERS (
    teacher_id      NUMBER(6)       NOT NULL,
    dept_id         NUMBER(5)       NOT NULL,       -- FK ? DEPARTMENTS: their home department
    first_name      VARCHAR2(50)    NOT NULL,
    last_name       VARCHAR2(50)    NOT NULL,
    email           VARCHAR2(100)   NOT NULL,       -- Must be unique — used for login/comms
    phone           VARCHAR2(15),                   -- Optional: not every teacher shares their number
    designation     VARCHAR2(50)    NOT NULL,       -- e.g. 'Lecturer', 'Assistant Professor', 'Professor'
    joining_date    DATE            NOT NULL,       -- When they joined the university
    
    CONSTRAINT pk_teachers      PRIMARY KEY (teacher_id),
    CONSTRAINT uq_teacher_email UNIQUE (email),
    
    -- Designation must be one of the official university ranks
    CONSTRAINT chk_designation CHECK (
        designation IN ('Lecturer', 'Assistant Professor', 'Associate Professor', 'Professor', 'Visiting Faculty')
    ),
    
    CONSTRAINT fk_teachers_dept FOREIGN KEY (dept_id) REFERENCES DEPARTMENTS(dept_id)
);

COMMENT ON TABLE  TEACHERS              IS 'Faculty members; each belongs to one home department';
COMMENT ON COLUMN TEACHERS.designation  IS 'Official academic rank at the university';
COMMENT ON COLUMN TEACHERS.email        IS 'Unique — used as the teacher identifier in systems';
--------------------------------------------------------------------------------
-- TABLE 4: COURSES
-- A course belongs to a program and is assigned to a teacher.
-- Design note: a course is a fixed offering (e.g. "OOP - Spring 2024").
-- Semesters/sections could be normalized further, but kept simple here.

CREATE SEQUENCE courses_seq
    START WITH 1
    INCREMENT BY 4
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE COURSES (
    course_id       NUMBER(6)       NOT NULL,
    program_id      NUMBER(5)       NOT NULL,       -- FK ? PROGRAMS: which program this course belongs to
    teacher_id      NUMBER(6),                      -- FK ? TEACHERS: who teaches it (NULL if unassigned yet)
    course_name     VARCHAR2(100)   NOT NULL,       -- e.g. 'Object Oriented Programming'
    course_code     VARCHAR2(20)    NOT NULL,       -- e.g. 'CS301', 'EE201'
    credit_hours    NUMBER(2)       NOT NULL,       -- Typically 3 (theory) or 1-2 (lab)
    semester        VARCHAR2(20)    NOT NULL,       -- e.g. 'Spring 2024', 'Fall 2025'
    
    CONSTRAINT pk_courses       PRIMARY KEY (course_id),
    CONSTRAINT uq_course_code   UNIQUE (course_code),
    
    -- Credit hours should be between 1 and 4 — no 0 or 10 credit courses
    CONSTRAINT chk_credit_hours CHECK (credit_hours BETWEEN 1 AND 4),
    
    CONSTRAINT fk_courses_program   FOREIGN KEY (program_id) REFERENCES PROGRAMS(program_id),
    
    -- SET NULL: if a teacher leaves/is deleted, course becomes unassigned rather than being deleted
    CONSTRAINT fk_courses_teacher   FOREIGN KEY (teacher_id) REFERENCES TEACHERS(teacher_id)
        ON DELETE SET NULL
);

COMMENT ON TABLE  COURSES               IS 'Course offerings linked to a program and a teacher';
COMMENT ON COLUMN COURSES.teacher_id    IS 'Nullable — course can be unassigned if teacher leaves';
COMMENT ON COLUMN COURSES.semester      IS 'e.g. Spring 2024, Fall 2025';
--------------------------------------------------------------------------------
-- TABLE 5: STUDENTS
-- Each student is enrolled in one program (their degree program).

CREATE SEQUENCE students_seq
    START WITH 1
    INCREMENT BY 3
    NOCACHE
    NOCYCLE;

CREATE TABLE STUDENTS (
    student_id          NUMBER(8)       NOT NULL,
    program_id          NUMBER(5)       NOT NULL,       -- FK ? PROGRAMS: their degree program
    first_name          VARCHAR2(50)    NOT NULL,
    last_name           VARCHAR2(50)    NOT NULL,
    email               VARCHAR2(100)   NOT NULL,
    phone               VARCHAR2(15),
    cnic                VARCHAR2(15),                   -- Pakistani national ID — optional for privacy
    date_of_birth       DATE,
    gender              VARCHAR2(10),
    admission_date      DATE            NOT NULL,
    current_semester    NUMBER(2)       NOT NULL,       -- Which semester they are currently in (1–8 for UG)
    status              VARCHAR2(20)    NOT NULL,       -- Active, Graduated, Dropped Out, On Leave
    
    CONSTRAINT pk_students      PRIMARY KEY (student_id),
    CONSTRAINT uq_student_email UNIQUE (email),
    
    -- Gender values only (NULL allowed — not mandatory to disclose)
    CONSTRAINT chk_gender CHECK (gender IN ('Male', 'Female', 'Other') OR gender IS NULL),
    
    -- Current semester should be a valid number (1–12 covers even long programs)
    CONSTRAINT chk_semester CHECK (current_semester BETWEEN 1 AND 12),
    
    -- Status must be one of the defined lifecycle states
    CONSTRAINT chk_student_status CHECK (
        status IN ('Active', 'Graduated', 'Dropped Out', 'On Leave', 'Suspended')
    ),
    
    CONSTRAINT fk_students_program FOREIGN KEY (program_id) REFERENCES PROGRAMS(program_id)
);

COMMENT ON TABLE  STUDENTS                  IS 'University students; each enrolled in one program';
COMMENT ON COLUMN STUDENTS.cnic             IS 'Pakistani CNIC — optional, stored for official records only';
COMMENT ON COLUMN STUDENTS.current_semester IS 'Semester the student is currently studying in';
COMMENT ON COLUMN STUDENTS.status          IS 'Lifecycle: Active, Graduated, Dropped Out, On Leave, Suspended';
--------------------------------------------------------------------------------
-- TABLE 6: ENROLLMENTS
-- The bridge between STUDENTS and COURSES.
-- A student can enroll in many courses; a course can have many students.
-- This is the classic many-to-many resolution table.
 CREATE SEQUENCE enrollments_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
 CREATE TABLE ENROLLMENTS (
    enrollment_id       NUMBER(10)      NOT NULL,
    student_id          NUMBER(8)       NOT NULL,       -- FK ? STUDENTS
    course_id           NUMBER(6)       NOT NULL,       -- FK ? COURSES
    enrollment_date     DATE            NOT NULL,       -- When they enrolled
    enrollment_status   VARCHAR2(20)    NOT NULL,       -- Enrolled, Dropped, Completed
    
    CONSTRAINT pk_enrollments   PRIMARY KEY (enrollment_id),
    
    -- A student cannot enroll in the same course twice at the same time
    -- This composite unique constraint prevents duplicate enrollments
    CONSTRAINT uq_enrollment UNIQUE (student_id, course_id),
    
    CONSTRAINT chk_enrollment_status CHECK (
        enrollment_status IN ('Enrolled', 'Dropped', 'Completed')
    ),
    
    CONSTRAINT fk_enrollment_student    FOREIGN KEY (student_id) REFERENCES STUDENTS(student_id),
    CONSTRAINT fk_enrollment_course     FOREIGN KEY (course_id)  REFERENCES COURSES(course_id)
);

 COMMENT ON TABLE  ENROLLMENTS                   IS 'Many-to-many bridge between STUDENTS and COURSES';
 COMMENT ON COLUMN ENROLLMENTS.enrollment_status IS 'Enrolled (active), Dropped (withdrew), Completed (finished)';
--------------------------------------------------------------------------------

-- TABLE 7: GRADES
-- Stores the final grade for each enrollment.
-- Linked to ENROLLMENTS (not directly to student/course) because a grade
-- only makes sense in the context of a specific enrollment.
-- Design note: one row per enrollment — final grade only, not per-assessment.

 CREATE SEQUENCE grades_seq
    START WITH 1
    INCREMENT BY 2
    NOCACHE
    NOCYCLE;

 CREATE TABLE GRADES (
    grade_id        NUMBER(10)      NOT NULL,
    enrollment_id   NUMBER(10)      NOT NULL,       -- FK ? ENROLLMENTS (unique: one grade per enrollment)
    marks_obtained  NUMBER(5,2),                    -- Out of 100, supports decimals e.g. 87.50
    grade_letter    VARCHAR2(5),                    -- A+, A, B+, B, C, D, F
    grade_points    NUMBER(3,2),                    -- GPA points e.g. 4.0, 3.7, 3.3
    remarks         VARCHAR2(200),                  -- Optional teacher remarks
    graded_on       DATE,                           -- When the grade was recorded
    
    CONSTRAINT pk_grades            PRIMARY KEY (grade_id),
    
    -- One grade per enrollment only — enforced by unique constraint
    CONSTRAINT uq_grade_enrollment  UNIQUE (enrollment_id),
    
    -- Marks must be between 0 and 100
    CONSTRAINT chk_marks CHECK (marks_obtained BETWEEN 0 AND 100 OR marks_obtained IS NULL),
    
    -- Valid grade letters in Pakistani university grading systems
    CONSTRAINT chk_grade_letter CHECK (
        grade_letter IN ('A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D', 'F', 'W', 'I')
        OR grade_letter IS NULL
        -- W = Withdrawn, I = Incomplete
    ),
    
    -- GPA points range: 0.0 to 4.0
    CONSTRAINT chk_grade_points CHECK (grade_points BETWEEN 0 AND 4 OR grade_points IS NULL),
    
    CONSTRAINT fk_grades_enrollment FOREIGN KEY (enrollment_id) REFERENCES ENROLLMENTS(enrollment_id)
);

COMMENT ON TABLE  GRADES                IS 'Final grade per enrollment; one row per student-course pairing';
COMMENT ON COLUMN GRADES.grade_letter   IS 'A+ to F; W=Withdrawn, I=Incomplete';
COMMENT ON COLUMN GRADES.grade_points   IS 'GPA scale 0.0–4.0';
--------------------------------------------------------------------------------
-- TABLE 8: ATTENDANCE
-- Tracks daily attendance per student per course.
-- Design note: ATTENDANCE links directly to student_id + course_id
-- (not to enrollment_id like GRADES does). This is a deliberate simplification —
-- it keeps attendance recording straightforward and avoids a join through ENROLLMENTS
-- for every attendance entry. The tradeoff: we don't enforce that the student
-- is actually enrolled (that would need a trigger or application logic).

CREATE SEQUENCE attendance_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

 CREATE TABLE ATTENDANCE (
    attendance_id       NUMBER(12)      NOT NULL,
    student_id          NUMBER(8)       NOT NULL,       -- FK ? STUDENTS
    course_id           NUMBER(6)       NOT NULL,       -- FK ? COURSES
    attendance_date     DATE            NOT NULL,       -- The specific class date
    status              VARCHAR2(10)    NOT NULL,       -- Present, Absent, Late
    remarks             VARCHAR2(200),                  -- Optional: reason for absence etc.
    
    CONSTRAINT pk_attendance    PRIMARY KEY (attendance_id),
    
    -- A student can only have one attendance record per course per date
    CONSTRAINT uq_attendance UNIQUE (student_id, course_id, attendance_date),
    
    CONSTRAINT chk_attendance_status CHECK (
        status IN ('Present', 'Absent', 'Late', 'Excused')
    ),
    
    CONSTRAINT fk_attendance_student    FOREIGN KEY (student_id) REFERENCES STUDENTS(student_id),
    CONSTRAINT fk_attendance_course     FOREIGN KEY (course_id)  REFERENCES COURSES(course_id)
);

COMMENT ON TABLE  ATTENDANCE                IS 'Daily attendance per student per course';
COMMENT ON COLUMN ATTENDANCE.status         IS 'Present, Absent, Late, or Excused';
COMMENT ON COLUMN ATTENDANCE.attendance_date IS 'The actual class date — one row per student per date per course';
--------------------------------------------------------------------------------
-- VERIFICATION: Run these after creation to confirm all objects exist

-- Check all tables were created:
 SELECT table_name FROM user_tables ORDER BY table_name;

-- Check all sequences were created:
 SELECT sequence_name, last_number FROM user_sequences ORDER BY sequence_name;

-- Check all constraints:
 SELECT constraint_name, constraint_type, table_name
 FROM user_constraints
 WHERE table_name IN ('DEPARTMENTS','PROGRAMS','TEACHERS','COURSES','STUDENTS','ENROLLMENTS','GRADES','ATTENDANCE')
 ORDER BY table_name, constraint_type;
 
 ------------------------------------------------------------------------------------------------------------
 -------------------------------------------------------------------------------------------------------------
 -- END OF MODULE 02
-- Next: Module 03 — INSERT data using sequence_name.NEXTVALg




    
    
    